[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  # Netlify now handles Node compatibility via environment variables
  directory = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200