/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTrademarkRouteImport } from './routes/services/trademark'
import { Route as ServicesRegisteredAddressRouteImport } from './routes/services/registered-address'
import { Route as ServicesProfitsTaxReturnRouteImport } from './routes/services/profits-tax-return'
import { Route as ServicesOffshoreCompanyRouteImport } from './routes/services/offshore-company'
import { Route as ServicesNamedSecretaryRouteImport } from './routes/services/named-secretary'
import { Route as ServicesMailForwardingRouteImport } from './routes/services/mail-forwarding'
import { Route as ServicesHkIncorporationRouteImport } from './routes/services/hk-incorporation'
import { Route as ServicesChangeOfDirectorsRouteImport } from './routes/services/change-of-directors'
import { Route as ServicesCallAnsweringRouteImport } from './routes/services/call-answering'
import { Route as ServicesBookkeepingRouteImport } from './routes/services/bookkeeping'
import { Route as ServicesAuditCoordinationRouteImport } from './routes/services/audit-coordination'
import { Route as ServicesAnnualReturnNar1RouteImport } from './routes/services/annual-return-nar1'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrademarkRoute = ServicesTrademarkRouteImport.update({
  id: '/services/trademark',
  path: '/services/trademark',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRegisteredAddressRoute =
  ServicesRegisteredAddressRouteImport.update({
    id: '/services/registered-address',
    path: '/services/registered-address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesProfitsTaxReturnRoute =
  ServicesProfitsTaxReturnRouteImport.update({
    id: '/services/profits-tax-return',
    path: '/services/profits-tax-return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesOffshoreCompanyRoute = ServicesOffshoreCompanyRouteImport.update({
  id: '/services/offshore-company',
  path: '/services/offshore-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNamedSecretaryRoute = ServicesNamedSecretaryRouteImport.update({
  id: '/services/named-secretary',
  path: '/services/named-secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMailForwardingRoute = ServicesMailForwardingRouteImport.update({
  id: '/services/mail-forwarding',
  path: '/services/mail-forwarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHkIncorporationRoute = ServicesHkIncorporationRouteImport.update({
  id: '/services/hk-incorporation',
  path: '/services/hk-incorporation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesChangeOfDirectorsRoute =
  ServicesChangeOfDirectorsRouteImport.update({
    id: '/services/change-of-directors',
    path: '/services/change-of-directors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCallAnsweringRoute = ServicesCallAnsweringRouteImport.update({
  id: '/services/call-answering',
  path: '/services/call-answering',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookkeepingRoute = ServicesBookkeepingRouteImport.update({
  id: '/services/bookkeeping',
  path: '/services/bookkeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAuditCoordinationRoute =
  ServicesAuditCoordinationRouteImport.update({
    id: '/services/audit-coordination',
    path: '/services/audit-coordination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAnnualReturnNar1Route =
  ServicesAnnualReturnNar1RouteImport.update({
    id: '/services/annual-return-nar1',
    path: '/services/annual-return-nar1',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/annual-return-nar1': typeof ServicesAnnualReturnNar1Route
  '/services/audit-coordination': typeof ServicesAuditCoordinationRoute
  '/services/bookkeeping': typeof ServicesBookkeepingRoute
  '/services/call-answering': typeof ServicesCallAnsweringRoute
  '/services/change-of-directors': typeof ServicesChangeOfDirectorsRoute
  '/services/hk-incorporation': typeof ServicesHkIncorporationRoute
  '/services/mail-forwarding': typeof ServicesMailForwardingRoute
  '/services/named-secretary': typeof ServicesNamedSecretaryRoute
  '/services/offshore-company': typeof ServicesOffshoreCompanyRoute
  '/services/profits-tax-return': typeof ServicesProfitsTaxReturnRoute
  '/services/registered-address': typeof ServicesRegisteredAddressRoute
  '/services/trademark': typeof ServicesTrademarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/annual-return-nar1': typeof ServicesAnnualReturnNar1Route
  '/services/audit-coordination': typeof ServicesAuditCoordinationRoute
  '/services/bookkeeping': typeof ServicesBookkeepingRoute
  '/services/call-answering': typeof ServicesCallAnsweringRoute
  '/services/change-of-directors': typeof ServicesChangeOfDirectorsRoute
  '/services/hk-incorporation': typeof ServicesHkIncorporationRoute
  '/services/mail-forwarding': typeof ServicesMailForwardingRoute
  '/services/named-secretary': typeof ServicesNamedSecretaryRoute
  '/services/offshore-company': typeof ServicesOffshoreCompanyRoute
  '/services/profits-tax-return': typeof ServicesProfitsTaxReturnRoute
  '/services/registered-address': typeof ServicesRegisteredAddressRoute
  '/services/trademark': typeof ServicesTrademarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/annual-return-nar1': typeof ServicesAnnualReturnNar1Route
  '/services/audit-coordination': typeof ServicesAuditCoordinationRoute
  '/services/bookkeeping': typeof ServicesBookkeepingRoute
  '/services/call-answering': typeof ServicesCallAnsweringRoute
  '/services/change-of-directors': typeof ServicesChangeOfDirectorsRoute
  '/services/hk-incorporation': typeof ServicesHkIncorporationRoute
  '/services/mail-forwarding': typeof ServicesMailForwardingRoute
  '/services/named-secretary': typeof ServicesNamedSecretaryRoute
  '/services/offshore-company': typeof ServicesOffshoreCompanyRoute
  '/services/profits-tax-return': typeof ServicesProfitsTaxReturnRoute
  '/services/registered-address': typeof ServicesRegisteredAddressRoute
  '/services/trademark': typeof ServicesTrademarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services/annual-return-nar1'
    | '/services/audit-coordination'
    | '/services/bookkeeping'
    | '/services/call-answering'
    | '/services/change-of-directors'
    | '/services/hk-incorporation'
    | '/services/mail-forwarding'
    | '/services/named-secretary'
    | '/services/offshore-company'
    | '/services/profits-tax-return'
    | '/services/registered-address'
    | '/services/trademark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services/annual-return-nar1'
    | '/services/audit-coordination'
    | '/services/bookkeeping'
    | '/services/call-answering'
    | '/services/change-of-directors'
    | '/services/hk-incorporation'
    | '/services/mail-forwarding'
    | '/services/named-secretary'
    | '/services/offshore-company'
    | '/services/profits-tax-return'
    | '/services/registered-address'
    | '/services/trademark'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services/annual-return-nar1'
    | '/services/audit-coordination'
    | '/services/bookkeeping'
    | '/services/call-answering'
    | '/services/change-of-directors'
    | '/services/hk-incorporation'
    | '/services/mail-forwarding'
    | '/services/named-secretary'
    | '/services/offshore-company'
    | '/services/profits-tax-return'
    | '/services/registered-address'
    | '/services/trademark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesAnnualReturnNar1Route: typeof ServicesAnnualReturnNar1Route
  ServicesAuditCoordinationRoute: typeof ServicesAuditCoordinationRoute
  ServicesBookkeepingRoute: typeof ServicesBookkeepingRoute
  ServicesCallAnsweringRoute: typeof ServicesCallAnsweringRoute
  ServicesChangeOfDirectorsRoute: typeof ServicesChangeOfDirectorsRoute
  ServicesHkIncorporationRoute: typeof ServicesHkIncorporationRoute
  ServicesMailForwardingRoute: typeof ServicesMailForwardingRoute
  ServicesNamedSecretaryRoute: typeof ServicesNamedSecretaryRoute
  ServicesOffshoreCompanyRoute: typeof ServicesOffshoreCompanyRoute
  ServicesProfitsTaxReturnRoute: typeof ServicesProfitsTaxReturnRoute
  ServicesRegisteredAddressRoute: typeof ServicesRegisteredAddressRoute
  ServicesTrademarkRoute: typeof ServicesTrademarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/trademark': {
      id: '/services/trademark'
      path: '/services/trademark'
      fullPath: '/services/trademark'
      preLoaderRoute: typeof ServicesTrademarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/registered-address': {
      id: '/services/registered-address'
      path: '/services/registered-address'
      fullPath: '/services/registered-address'
      preLoaderRoute: typeof ServicesRegisteredAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/profits-tax-return': {
      id: '/services/profits-tax-return'
      path: '/services/profits-tax-return'
      fullPath: '/services/profits-tax-return'
      preLoaderRoute: typeof ServicesProfitsTaxReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/offshore-company': {
      id: '/services/offshore-company'
      path: '/services/offshore-company'
      fullPath: '/services/offshore-company'
      preLoaderRoute: typeof ServicesOffshoreCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/named-secretary': {
      id: '/services/named-secretary'
      path: '/services/named-secretary'
      fullPath: '/services/named-secretary'
      preLoaderRoute: typeof ServicesNamedSecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mail-forwarding': {
      id: '/services/mail-forwarding'
      path: '/services/mail-forwarding'
      fullPath: '/services/mail-forwarding'
      preLoaderRoute: typeof ServicesMailForwardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hk-incorporation': {
      id: '/services/hk-incorporation'
      path: '/services/hk-incorporation'
      fullPath: '/services/hk-incorporation'
      preLoaderRoute: typeof ServicesHkIncorporationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/change-of-directors': {
      id: '/services/change-of-directors'
      path: '/services/change-of-directors'
      fullPath: '/services/change-of-directors'
      preLoaderRoute: typeof ServicesChangeOfDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/call-answering': {
      id: '/services/call-answering'
      path: '/services/call-answering'
      fullPath: '/services/call-answering'
      preLoaderRoute: typeof ServicesCallAnsweringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bookkeeping': {
      id: '/services/bookkeeping'
      path: '/services/bookkeeping'
      fullPath: '/services/bookkeeping'
      preLoaderRoute: typeof ServicesBookkeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/audit-coordination': {
      id: '/services/audit-coordination'
      path: '/services/audit-coordination'
      fullPath: '/services/audit-coordination'
      preLoaderRoute: typeof ServicesAuditCoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/annual-return-nar1': {
      id: '/services/annual-return-nar1'
      path: '/services/annual-return-nar1'
      fullPath: '/services/annual-return-nar1'
      preLoaderRoute: typeof ServicesAnnualReturnNar1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesAnnualReturnNar1Route: ServicesAnnualReturnNar1Route,
  ServicesAuditCoordinationRoute: ServicesAuditCoordinationRoute,
  ServicesBookkeepingRoute: ServicesBookkeepingRoute,
  ServicesCallAnsweringRoute: ServicesCallAnsweringRoute,
  ServicesChangeOfDirectorsRoute: ServicesChangeOfDirectorsRoute,
  ServicesHkIncorporationRoute: ServicesHkIncorporationRoute,
  ServicesMailForwardingRoute: ServicesMailForwardingRoute,
  ServicesNamedSecretaryRoute: ServicesNamedSecretaryRoute,
  ServicesOffshoreCompanyRoute: ServicesOffshoreCompanyRoute,
  ServicesProfitsTaxReturnRoute: ServicesProfitsTaxReturnRoute,
  ServicesRegisteredAddressRoute: ServicesRegisteredAddressRoute,
  ServicesTrademarkRoute: ServicesTrademarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
